import { useCallback, useEffect, useState, type FormEvent } from "react";

import { createApplication, listApplications, updateApplication } from "./api";
import { EmptyState, Field, LoadingRows, Modal, PAGE_SIZE, Pager, SearchBox, StatusBadge, emptyPagination, useDebouncedValue, type ErrorHandler, type Notify } from "./components";
import { CheckIcon, EditIcon, PlusIcon } from "./icons";
import type { AdminRole, Application } from "./types";
import { can, formatDuration } from "./ui";

export function ApplicationFormModal({ application, onClose, onSaved, onError }: { application?: Application; onClose: () => void; onSaved: () => void; onError: ErrorHandler }) {
  const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setBusy(true); const payload = { name: String(data.get("name") || ""), appCode: String(data.get("appCode") || "").toUpperCase(), description: String(data.get("description") || "").trim() || null, currentVersion: String(data.get("currentVersion") || "").trim() || null, minimumVersion: String(data.get("minimumVersion") || "").trim() || null, status: String(data.get("status") || "ACTIVE") as "ACTIVE" | "DISABLED", offlineGraceSeconds: Number(data.get("offlineGraceSeconds")), defaultDeviceLimit: Number(data.get("defaultDeviceLimit")), defaultDurationDays: Number(data.get("defaultDurationDays")), allowLifetime: data.get("allowLifetime") === "on" }; try { if (application) await updateApplication(application.id, payload); else await createApplication(payload as Omit<Application, "id" | "createdAt" | "updatedAt">); onSaved(); } catch (error) { onError(error); } finally { setBusy(false); } }
  return <Modal title={application ? "Cấu hình ứng dụng" : "Thêm ứng dụng"} subtitle="Mỗi license chỉ hợp lệ cho đúng application được cấp." onClose={onClose} wide><form className="modal-form" onSubmit={submit}><div className="form-grid two"><Field label="Tên ứng dụng"><input name="name" defaultValue={application?.name || ""} required /></Field><Field label="App code" hint="2–32 ký tự A-Z, 0-9, _ hoặc -"><input name="appCode" defaultValue={application?.appCode || ""} required /></Field></div><Field label="Mô tả"><textarea name="description" rows={2} defaultValue={application?.description || ""} /></Field><div className="form-grid three"><Field label="Current version"><input name="currentVersion" defaultValue={application?.currentVersion || ""} placeholder="1.0.0" /></Field><Field label="Minimum version"><input name="minimumVersion" defaultValue={application?.minimumVersion || ""} placeholder="1.0.0" /></Field><Field label="Trạng thái"><select name="status" defaultValue={application?.status || "ACTIVE"}><option value="ACTIVE">ACTIVE</option><option value="DISABLED">DISABLED</option></select></Field></div><div className="form-grid three"><Field label="Offline grace (giây)"><input name="offlineGraceSeconds" type="number" min="0" max="2592000" defaultValue={application?.offlineGraceSeconds ?? 86400} required /></Field><Field label="Device mặc định"><input name="defaultDeviceLimit" type="number" min="1" max="32767" defaultValue={application?.defaultDeviceLimit ?? 1} required /></Field><Field label="Thời hạn mặc định (ngày)"><input name="defaultDurationDays" type="number" min="1" max="36500" defaultValue={application?.defaultDurationDays ?? 30} required /></Field></div><label className="checkbox-row"><input name="allowLifetime" type="checkbox" defaultChecked={application?.allowLifetime ?? true} /><span><strong>Cho phép license vĩnh viễn</strong><small>Admin có thể tạo hoặc chuyển license sang LIFETIME.</small></span></label><div className="modal-actions"><button className="button ghost" type="button" onClick={onClose}>Hủy</button><button className="button primary" type="submit" disabled={busy}>{busy ? <span className="spinner" /> : <CheckIcon size={17} />} Lưu cấu hình</button></div></form></Modal>;
}

export function ApplicationsPage({ role, onError, notify }: { role: AdminRole; onError: ErrorHandler; notify: Notify }) {
  const [items, setItems] = useState<Application[]>([]); const [pagination, setPagination] = useState(emptyPagination); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [offset, setOffset] = useState(0); const [loading, setLoading] = useState(true); const [editing, setEditing] = useState<Application | "new" | null>(null); const debouncedSearch = useDebouncedValue(search);
  const load = useCallback(async () => { setLoading(true); try { const result = await listApplications({ q: debouncedSearch, status, limit: PAGE_SIZE, offset }); setItems(result.applications); setPagination(result.pagination); } catch (error) { onError(error); } finally { setLoading(false); } }, [debouncedSearch, offset, onError, status]);
  useEffect(() => { void load(); }, [load]); useEffect(() => setOffset(0), [debouncedSearch, status]);
  return <div className="page"><div className="page-heading"><div><span className="eyebrow dark">APPLICATIONS</span><h1>Ứng dụng</h1><p>Cấu hình version, offline grace và chính sách license theo từng Desktop App.</p></div>{can(role, "application:write") ? <button className="button primary" type="button" onClick={() => setEditing("new")}><PlusIcon size={18} /> Thêm ứng dụng</button> : null}</div><section className="panel"><div className="toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Tên hoặc app code..." /><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Mọi trạng thái</option><option value="ACTIVE">ACTIVE</option><option value="DISABLED">DISABLED</option></select></div><div className="table-wrap"><table><thead><tr><th>Ứng dụng</th><th>Version</th><th>Offline grace</th><th>Mặc định license</th><th>Trạng thái</th><th /></tr></thead><tbody>{loading ? <LoadingRows columns={6} /> : items.map((item) => <tr key={item.id}><td><div className="cell-title"><span className="app-avatar large-avatar">{item.appCode.slice(0, 2)}</span><div><strong>{item.name}</strong><small>{item.appCode}</small></div></div></td><td><div className="cell-stack"><strong>{item.currentVersion || "—"}</strong><small>Minimum {item.minimumVersion || "—"}</small></div></td><td>{formatDuration(item.offlineGraceSeconds)}</td><td><div className="cell-stack"><strong>{item.defaultDurationDays} ngày · {item.defaultDeviceLimit} device</strong><small>{item.allowLifetime ? "Cho phép lifetime" : "Không lifetime"}</small></div></td><td><StatusBadge status={item.status} /></td><td>{can(role, "application:write") ? <button className="icon-button small" type="button" onClick={() => setEditing(item)} aria-label="Sửa"><EditIcon size={16} /></button> : null}</td></tr>)}</tbody></table>{!loading && items.length === 0 ? <EmptyState title="Chưa có application" body="Thêm Desktop App đầu tiên để bắt đầu cấp license." /> : null}</div><Pager pagination={pagination} onOffset={setOffset} /></section>{editing ? <ApplicationFormModal application={editing === "new" ? undefined : editing} onClose={() => setEditing(null)} onError={onError} onSaved={() => { notify(editing === "new" ? "Đã tạo application" : "Đã cập nhật application"); setEditing(null); void load(); }} /> : null}</div>;
}
