import { useCallback, useEffect, useState } from "react";

import { listDevices, revokeDevice } from "./api";
import { EmptyState, LoadingRows, PAGE_SIZE, Pager, SearchBox, StatusBadge, emptyPagination, useDebouncedValue, type ErrorHandler, type Notify } from "./components";
import { MonitorIcon, RefreshIcon } from "./icons";
import type { AdminRole, Device } from "./types";
import { can, formatDateTime } from "./ui";

export function DevicesPage({ role, onError, notify }: { role: AdminRole; onError: ErrorHandler; notify: Notify }) {
  const [items, setItems] = useState<Device[]>([]); const [pagination, setPagination] = useState(emptyPagination); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [offset, setOffset] = useState(0); const [loading, setLoading] = useState(true); const debouncedSearch = useDebouncedValue(search);
  const load = useCallback(async () => { setLoading(true); try { const result = await listDevices({ q: debouncedSearch, status, limit: PAGE_SIZE, offset }); setItems(result.devices); setPagination(result.pagination); } catch (error) { onError(error); } finally { setLoading(false); } }, [debouncedSearch, offset, onError, status]);
  useEffect(() => { void load(); }, [load]); useEffect(() => setOffset(0), [debouncedSearch, status]);
  async function revoke(item: Device) { if (!window.confirm(`Revoke thiết bị ${item.deviceName || item.deviceId}? Thiết bị này sẽ không thể tự kích hoạt lại.`)) return; try { await revokeDevice(item.id); notify("Đã revoke thiết bị"); void load(); } catch (error) { onError(error); } }
  return <div className="page"><div className="page-heading"><div><span className="eyebrow dark">DEVICES</span><h1>Thiết bị</h1><p>Theo dõi activation và thu hồi thiết bị khi cần.</p></div><button className="button secondary" type="button" onClick={() => void load()}><RefreshIcon size={17} /> Làm mới</button></div><section className="panel"><div className="toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Device ID, máy, OS, license..." /><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Mọi trạng thái</option><option value="ACTIVE">ACTIVE</option><option value="INACTIVE">INACTIVE</option><option value="REVOKED">REVOKED</option></select></div><div className="table-wrap"><table><thead><tr><th>Thiết bị</th><th>Ứng dụng</th><th>License</th><th>Khách hàng</th><th>Last seen</th><th>Trạng thái</th><th /></tr></thead><tbody>{loading ? <LoadingRows columns={7} /> : items.map((item) => <tr key={item.id}><td><div className="cell-title"><span className="device-avatar"><MonitorIcon size={18} /></span><div><strong>{item.deviceName || "Unnamed device"}</strong><small className="mono compact">{item.deviceId}</small></div></div></td><td><div className="cell-stack"><strong>{item.applicationName}</strong><small>{item.appCode} · {item.appVersion || "?"}</small></div></td><td><span className="mono">{item.licenseKeyPreview}</span></td><td>{item.customerName || <span className="muted">—</span>}</td><td><div className="cell-stack"><strong>{formatDateTime(item.lastSeenAt)}</strong><small>{item.os || "Unknown OS"}</small></div></td><td><StatusBadge status={item.status} /></td><td>{can(role, "device:revoke") && item.status !== "REVOKED" ? <button className="button danger-soft tiny" type="button" onClick={() => void revoke(item)}>Revoke</button> : null}</td></tr>)}</tbody></table>{!loading && items.length === 0 ? <EmptyState title="Chưa có thiết bị" body="Thiết bị sẽ xuất hiện sau khi Desktop App kích hoạt license." /> : null}</div><Pager pagination={pagination} onOffset={setOffset} /></section></div>;
}
